2024-10-30 16:50:25.904 - componentLogger - Launcher.startup - ERROR - 组件注册运行发生异常:<AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused", grpc_status:14, created_time:"2024-10-30T08:50:25.8772073+00:00"}"
>
Traceback (most recent call last):
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\ApplicationFramework\launcher\Launcher.py", line 86, in startup
    await self.__component_framework.register_component(component_model)
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\ApplicationFramework\facade\ComponentFrameworkImplement.py", line 93, in register_component
    registered_component: ComponentModel_CCM = await self.__component_manager.component_register(
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\componentframework\control\ComponentManagerInterfaceImpl.py", line 44, in component_register
    self.component_register_result = await self.__component_forwarder.component_register(component_model)
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\componentframework\service\ComponentManagerService.py", line 48, in component_register
    self.component_register_result = await self.__component_forwarder.component_register(component_model)
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\componentframework\facadeImpl\ComponentManagerFacadeImpl.py", line 57, in component_register
    response = await self.stub.RegisterComponent(request)
  File "C:\Users\dog\Desktop\hardSoft\Python310\lib\site-packages\grpc\aio\_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused", grpc_status:14, created_time:"2024-10-30T08:50:25.8772073+00:00"}"
>
2024-10-30 16:50:25.945 - componentLogger - Launcher.shutdown - ERROR - 组件注销发生异常:<AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused", grpc_status:14, created_time:"2024-10-30T08:50:25.9267169+00:00"}"
>
Traceback (most recent call last):
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\ApplicationFramework\launcher\Launcher.py", line 97, in shutdown
    await self.__component_framework.unregister_component()
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\ApplicationFramework\facade\ComponentFrameworkImplement.py", line 105, in unregister_component
    await self.__component_manager.unregister_component()
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\componentframework\control\ComponentManagerInterfaceImpl.py", line 129, in unregister_component
    self.unregister_component_result = await self.__component_forwarder.unregister_component()
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\componentframework\service\ComponentManagerService.py", line 133, in unregister_component
    self.unregister_component_result = await self.__component_forwarder.unregister_component()
  File "C:\Users\dog\Desktop\hardSoft\app\Collector\componentframework\facadeImpl\ComponentManagerFacadeImpl.py", line 145, in unregister_component
    response = await self.stub.UnregisterComponent(request)
  File "C:\Users\dog\Desktop\hardSoft\Python310\lib\site-packages\grpc\aio\_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9002: Connection refused", grpc_status:14, created_time:"2024-10-30T08:50:25.9267169+00:00"}"
>
